### ISSUE TITLE
NullPointerException on compare

### ISSUE THREAD

**Issue by ckandirali** [lukecnau/getStringLength#6]
After compare editor is opened from team view or package explorer NPE error is occured. This is the stacktrace of error:

java.lang.NullPointerException
	at com.lyf.plugin.getStringLength.SelectedTextInfoControlContribution.updateSelection(SelectedTextInfoControlContribution.java:61)
	at com.lyf.plugin.getStringLength.TextSelectionListener.selectionChanged(TextSelectionListener.java:25)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:240)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:176)
	at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3174)
	at org.eclipse.ui.internal.WorkbenchPage$3.run(WorkbenchPage.java:4905)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4902)
	at org.eclipse.ui.internal.WorkbenchPage.access$3(WorkbenchPage.java:4887)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:214)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:253)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:250)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:775)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:679)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3217)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3114)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3112)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3083)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3074)
	at org.eclipse.compare.internal.CompareUIPlugin.lambda$0(CompareUIPlugin.java:573)
	at org.eclipse.compare.internal.CompareUIPlugin.syncExec(CompareUIPlugin.java:1406)
	at org.eclipse.compare.internal.CompareUIPlugin.internalOpenEditor(CompareUIPlugin.java:583)
	at org.eclipse.compare.internal.CompareUIPlugin.openEditorInBackground(CompareUIPlugin.java:555)
	at org.eclipse.compare.internal.CompareUIPlugin.openCompareEditor(CompareUIPlugin.java:544)
	at org.eclipse.compare.CompareUI.openCompareEditorOnPage(CompareUI.java:174)
	at org.eclipse.compare.CompareUI.openCompareEditor(CompareUI.java:143)
	at org.eclipse.compare.CompareUI.openCompareEditor(CompareUI.java:127)
	at org.eclipse.team.internal.ui.actions.CompareAction.openInCompare(CompareAction.java:102)
	at org.eclipse.team.internal.ui.actions.CompareAction.execute(CompareAction.java:79)
	at org.eclipse.team.internal.ui.actions.TeamAction.run(TeamAction.java:556)
	at org.eclipse.team.internal.ui.actions.TeamAction.runWithEvent(TeamAction.java:592)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:222)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

Thanks a lot.

**Comment by lukecnau** [comment]
Hi, sorry about that low level failure. I should check whether it's null before call a String's function.

Please try it by downloading from https://github.com/lukecnau/getStringLength/blob/master/dist/plugins/com.lyf.plugin.getStringLength_1.0.4.201907201141.jar

Thank you very much!

**Comment by ckandirali** [comment]
Hi, I tried your new jar and no NPE is occured. 
Thanks a lot.
